### ISSUE TITLE
А как допустим сделать прошивку для ESP32-2432S024?

### ISSUE THREAD

**Issue by Asmodeux2** [smoochiee/MARAUDER-FOR-CYD---CHEAP-YELLOW-DISPLAY#1]
Долго просто с этим мучаюсь и не понимаю

**Comment by Jasurios1** [comment]
when you do it write to me I have the same problem

**Comment by ATOMNFT** [comment]
> Долго просто с этим мучаюсь и не понимаю

Что ты не понимаешь? Может быть, я смогу помочь.

**Comment by Asmodeux2** [comment]
Да, код не компилируется. Делаю всё по инструкции, версии ESP-IDF все перепробовал, Версии Arduino IDE тоже разные пробовал.

**Comment by ATOMNFT** [comment]
> Да, код не компилируется. Делаю всё по инструкции, версии ESP-IDF все перепробовал, Версии Arduino IDE тоже разные пробовал.

Можете ли вы сказать мне, какие ошибки появляются? Возможно, ошибка даст некоторое представление о том, что происходит или не происходит.

**Comment by Asmodeux2** [comment]
Их слишком много, при любой версии. Укажите просто какие библиотеки вы использовали и какой версии у вас библиотека ESP32 в Manage Libraries. И думаю у меня получится скомпилировать

**Comment by ATOMNFT** [comment]
Вот библиотеки, необходимые для компиляции. lv_arduino LinkedList TFT_eSPI JPEGDecoder library NimBLE NeoPixel ArduinoJson SwitchLib ESPAsyncWebServer AsyncTCP Установите драйверы CP210X. Установите драйверы CH340X. Перейдите в Tools>Board>Boards Manager, найдите esp32 и установите esp32 от Espressif Systems. Убедитесь, что это версия 2.0.10. Убедитесь, что вы отредактировали platform.txt. Надеюсь, это поможет, и надеюсь, что Google Translate все правильно понял.
