### ISSUE TITLE
Please help me i dont have the packages folder 

### ISSUE THREAD

**Issue by VuDucVN-tech12** [smoochiee/MARAUDER-FOR-CYD---CHEAP-YELLOW-DISPLAY#2]
C:\Users\USERNAME\AppData\Local\Arduino15\packages\esp32\hardware\esp32

**Comment by ATOMNFT** [comment]
> C:\Users\USERNAME\AppData\Local\Arduino15\packages\esp32\hardware\esp32

Did you install esp32 by Espressif Systems? 
Step 4. "Go to Tools>Board>Boards Manager, search for esp32 and install esp32 by Espressif Systems"

**Comment by smoochiee** [comment]
> C:\Users\USERNAME\AppData\Local\Arduino15\packages\esp32\hardware\esp32

nah..if you read it.. USERNAME should be your computer name...

**Comment by ATOMNFT** [comment]
Example:
C:\Users\VuDucVN\AppData\Local\Arduino15\packages\esp32\hardware\esp32
This part ^^^^^^ should be replaced with the username of the pc.

**Comment by VuDucVN-tech12** [comment]
> Referenc

Sorry to bother u. When verifying, it just stuck at compiling the sketch. How do i fix it
![Screenshot (173)](https://github.com/user-attachments/assets/06e9fc88-810e-4d99-9e6b-86566c5fd4cc)

**Comment by VuDucVN-tech12** [comment]
> > C:\Users\USERNAME\AppData\Local\Arduino15\packages\esp32\hardware\esp32
> 
> nah..if you read it.. USERNAME should be your computer name...

thank u. I have uploaded the code successfully. Im powering the CYD using lipo battery so is there any chances to display the battery level on the Marauder ?

**Comment by smoochiee** [comment]
> > > C:\Users\USERNAME\AppData\Local\Arduino15\packages\esp32\hardware\esp32
> > 
> > nah..if you read it.. USERNAME should be your computer name...
> 
> thank u. I have uploaded the code successfully. Im powering the CYD using lipo battery so is there any chances to display the battery level on the Marauder ?
> 

no you need battery gauge
